### ISSUE TITLE
How should we handle non-UTF8 in path data?

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-api#38]
Currently, the path segment deserialization code uses `decode_utf8_lossy` from percent-encoding. This is very unlikely to come up in practice, but we should still think about whether this makes sense. Does the matrix spec say anything about it?

**Comment by ldm0** [comment]
Yep, I did some search on it. It turns out that in Matrix's [`Client-Server API`](https://matrix.org/docs/spec/client_server/r0.6.0#api-standards), [`Server-Server API`](https://matrix.org/docs/spec/server_server/r0.1.3#api-standards) and [`Identitiy Service API`](https://matrix.org/docs/spec/identity_service/r0.3.0#api-standards) specs we get:

> strings MUST be encoded as UTF-8.

But there is no such constraint in [`Application Service API`](https://matrix.org/docs/spec/application_service/r0.1.2) and [`Push Gateway API`](https://matrix.org/docs/spec/push_gateway/r0.1.1). 

That's strange.

**Comment by ldm0** [comment]
Wait, I think they just forget to mention it. They even forgot to mention the obvious(I guess) `application/json` constraint. :-P

**Comment by jplatte** [comment]
Seems like we should error on invalid UTF-8 then.

**Comment by jplatte** [comment]
Closing in favor of #43.
